#!/bin/sh
# ThunderLink universal Linux installer/self-extractor.
# Embeds both aarch64 and x86_64 AppImages; runs the right one on execution.
#
# Generated by scripts/build-universal-appimage.sh — do not edit the
# binary payload below the marker line.
#
# Usage:
#   ./ThunderLink_universal.sh          (run the desktop app)
#   ./ThunderLink_universal.sh --cli    (run the CLI instead)
#   TL_EXTRACT_ONLY=1 ./ThunderLink_universal.sh   (extract to ./ThunderLink/)
set -e

ARCH="$(uname -m)"
case "$ARCH" in
    x86_64|amd64)  ARCH="amd64" ;;
    aarch64|arm64) ARCH="aarch64" ;;
    *)
        echo "ThunderLink: unsupported architecture: $ARCH" >&2
        exit 1
        ;;
esac

# ---- locate the embedded payload ----------------------------------------
# The payload starts right after the marker line; each AppImage is stored
# as a base64 block delimited by arch tags.
SCRIPT="$0"
PAYLOAD_START=$(grep -n "^# __PAYLOAD_BELOW__" "$SCRIPT" | head -1 | cut -d: -f1)
if [ -z "$PAYLOAD_START" ]; then
    echo "ThunderLink: payload marker not found (corrupted download?)" >&2
    exit 1
fi
PAYLOAD_LINE=$((PAYLOAD_START + 1))

# ---- extract or run ------------------------------------------------------
TMPDIR="${TMPDIR:-/tmp}/thunderlink-$$"
mkdir -p "$TMPDIR"

echo "ThunderLink: extracting $ARCH AppImage..." >&2
sed -n "${PAYLOAD_LINE},\$p" "$SCRIPT" | \
    sed -n "/^# BEGIN_${ARCH}$/,/^# END_${ARCH}$/p" | \
    grep -v "^# \(BEGIN\|END\)" | \
    base64 -d > "$TMPDIR/ThunderLink.AppImage"

chmod +x "$TMPDIR/ThunderLink.AppImage"
SIZE=$(stat -c%s "$TMPDIR/ThunderLink.AppImage" 2>/dev/null || wc -c < "$TMPDIR/ThunderLink.AppImage")
if [ "$SIZE" -lt 1000000 ]; then
    echo "ThunderLink: extraction failed ($SIZE bytes — expected > 1 MB)" >&2
    rm -rf "$TMPDIR"
    exit 1
fi
echo "ThunderLink: extracted $(( SIZE / 1048576 )) MB" >&2

if [ -n "$TL_EXTRACT_ONLY" ]; then
    mkdir -p "$(pwd)/ThunderLink"
    mv "$TMPDIR/ThunderLink.AppImage" "$(pwd)/ThunderLink/"
    echo "ThunderLink: extracted to $(pwd)/ThunderLink/ThunderLink.AppImage" >&2
    rm -rf "$TMPDIR"
    exit 0
fi

# FUSE-less environments (containers, some distros): extract-and-run
if ! fusermount -v >/dev/null 2>&1 && [ ! -e /dev/fuse ]; then
    exec "$TMPDIR/ThunderLink.AppImage" --appimage-extract-and-run "$@"
fi

exec "$TMPDIR/ThunderLink.AppImage" "$@"
exit  # unreachable — payload below

# __PAYLOAD_BELOW__
# The build script appends:
# # BEGIN_aarch64
# <base64 of aarch64 AppImage>
# # END_aarch64
# # BEGIN_amd64
# <base64 of x86_64 AppImage>
# # END_amd64
